#input
width = int(input('enter the width: '))
height= int(input('enter height: '))
#process
rec_width = width/5

import turtle
turtle.color('yellow')
turtle.begin_fill()
turtle.forward(rec_width)
turtle.setheading(90)
turtle.forward(height)
turtle.setheading(180)
turtle.forward(rec_width)
turtle.setheading(270)
turtle.forward(height)
turtle.end_fill()
turtle.color('green')
turtle.begin_fill()
turtle.setheading(90)
turtle.forward(height)
turtle.setheading(180)
turtle.forward(rec_width)
turtle.setheading(270)
turtle.forward(height)
turtle.end_fill()
turtle.color('orange')
turtle.begin_fill()
turtle.setheading(90)
turtle.forward(height)
turtle.setheading(180)
turtle.forward(rec_width)
turtle.setheading(270)
turtle.forward(height)
turtle.end_fill()
turtle.color('blue')
turtle.begin_fill()
turtle.setheading(90)
turtle.forward(height)
turtle.setheading(180)
turtle.forward(rec_width)
turtle.setheading(270)
turtle.forward(height)
turtle.end_fill()
turtle.color('red')
turtle.begin_fill()
turtle.setheading(90)
turtle.forward(height)
turtle.setheading(180)
turtle.forward(rec_width)
turtle.setheading(270)
turtle.forward(height)
turtle.end_fill()
turtle.done()
